name: Spec Tests

on:
  push:
    paths:
      - 'mainnet-1/specs/*.json'  
  pull_request:
    paths:
      - 'mainnet-1/specs/*.json'  
  # Optionally allow manual triggers
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Specs Repository
        uses: actions/checkout@v3
        with:
          path: specs-repo

      - name: Checkout Lava Repository
        uses: actions/checkout@v3
        with:
          repository: lavanet/lava  # Replace with the correct repository
          path: lava
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Create Symlink for Specs
        run: |
          rm -rf lava/cookbook/specs
          ln -s $GITHUB_WORKSPACE/specs-repo/specs lava/cookbook/specs

      - name: Run Tests
        working-directory: lava/x/spec/keeper
        run: go test -v -run TestCookbookSpecs