name: Spec Tests

on:
  pull_request:
    paths:
      - 'mainnet-1/specs/*.json'  
  # Optionally allow manual triggers
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4

      - name: Get latest tag
        id: latest_tag
        run: |
          echo "tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_OUTPUT

      - name: Checkout Lava Repository
        uses: actions/checkout@v4
        with:
          repository: lavanet/lava
          path: lava
          fetch-depth: 0
          ref: ${{ steps.latest_tag.outputs.tag }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Copy specs to lava
        run: |
          rm -rf lava/cookbook/specs
          cp -r $GITHUB_WORKSPACE/mainnet-1/specs lava/cookbook/specs

      - name: Run Tests
        working-directory: lava/x/spec/keeper
        run: go test -v -run TestCookbookSpecs